"""Idempotent node provisioning (Stage 14A, area 3).

``provision_node`` creates the production directory layout with restrictive permissions,
optionally generates an initial configuration from a template, and initializes/migrates the
database — all idempotently and non-destructively. It NEVER overwrites an existing identity or
database silently, supports a dry-run that creates nothing, and is non-interactive. Identity is
generated only when explicitly requested (the node initializes it on first start otherwise).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

from aithernet.ops.paths import NodePaths


@dataclass
class ProvisionResult:
    dry_run: bool
    state_root: str
    created_dirs: list[str] = field(default_factory=list)
    existing_dirs: list[str] = field(default_factory=list)
    actions: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    config_written: bool = False
    database_migrated: bool = False

    def to_dict(self) -> dict:
        return {
            "dry_run": self.dry_run, "state_root": self.state_root,
            "created_dirs": self.created_dirs, "existing_dirs": self.existing_dirs,
            "actions": self.actions, "skipped": self.skipped,
            "config_written": self.config_written, "database_migrated": self.database_migrated,
        }


CONFIG_TEMPLATE = """# Aithernet node configuration (generated by `aithernet node provision`).
# Edit before first start. Wire secrets via the environment, never inline here.
node_id: "{node_id}"
node_name: "{node_name}"
node_state_root: "{state_root}"
database_url: "sqlite:///{db_file}"
host: "127.0.0.1"
port: 8080
log_level: "info"

agent_transport:
  enabled: true
  identity:
    state_directory: "{identity_dir}"
    auto_initialize: false        # generate via `aithernet identity initialize` (never silently)

artifacts:
  enabled: true
  state_directory: "{artifacts_dir}"

# coordinator / coding_agent / rf_backends: copy from configs/node.yaml and point any
# workspaces beneath the state root. Marconi stays experimental + non-autostart.
"""


def provision_node(
    state_root: str | Path,
    *,
    node_id: str,
    node_name: str,
    dry_run: bool = False,
    write_config: bool = True,
    migrate: bool = True,
) -> ProvisionResult:
    """Create the node layout + (optionally) an initial config and migrated database.

    Idempotent: existing directories are left as-is; an existing config or database is never
    overwritten (it is reported as ``skipped``). ``dry_run`` performs no filesystem writes.
    """
    paths = NodePaths.from_root(state_root)
    result = ProvisionResult(dry_run=dry_run, state_root=str(paths.root))

    # -- directories -------------------------------------------------------------
    for directory, mode in paths.all_dirs():
        if directory.exists():
            result.existing_dirs.append(str(directory))
            continue
        result.created_dirs.append(str(directory))
        if not dry_run:
            directory.mkdir(parents=True, exist_ok=True)
            os.chmod(directory, mode)

    # -- initial configuration (never overwrite an existing one) -----------------
    if write_config:
        if paths.config_file.exists():
            result.skipped.append(f"config exists: {paths.config_file}")
        else:
            result.config_written = True
            result.actions.append(f"write config: {paths.config_file}")
            if not dry_run:
                paths.config_file.write_text(
                    CONFIG_TEMPLATE.format(
                        node_id=node_id, node_name=node_name, state_root=str(paths.root),
                        db_file=str(paths.database_file), identity_dir=str(paths.identity_dir),
                        artifacts_dir=str(paths.artifacts_dir),
                    )
                )
                os.chmod(paths.config_file, 0o640)

    # -- database initialize + migrate (never destroys existing data) ------------
    if migrate:
        if paths.database_file.exists():
            result.skipped.append(f"database exists: {paths.database_file} (will migrate in place)")
        result.actions.append("migrate database")
        result.database_migrated = True
        if not dry_run:
            from aithernet.state.db import create_db_engine
            from aithernet.state.migrations import run_migrations

            engine = create_db_engine(paths.database_url)
            run_migrations(engine)
            engine.dispose()

    return result
